# Generated by Django 4.0.4 on 2022-06-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0003_alter_user_date_of_birth_alter_user_personal_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
