# Generated by Django 4.0.4 on 2022-06-18 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0008_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='gym_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gym_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
